---
name: "Build"
on:
  "pull_request"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4"

      - name: "install Nix"
        uses: "cachix/install-nix-action@v31"

      - name: "use project cache"
        uses: cachix/cachix-action@v16
        with:
          name: svsticky-aas
          authToken: ${{ secrets.CACHIX_API_KEY }}

      - name: "build aas"
        run: "nix-build"

